### ISSUE TITLE
Name of icons with dash

### ISSUE THREAD

**Issue by ocelhay** [mitchelloharawild/icon#15]
`fontawesome("dungeon")` works as expected while
`fontawesome("people-arrows")
Error: The `people` icon could not be found in this icon set.`

All the icons I have tried with a name containing a `-` throw the same error.

**Comment by mitchelloharawild** [comment]
The fontawesome `"people-arrows"` is part of the pro library which will need to be loaded in via a custom icon set.

**Comment by ocelhay** [comment]
Sorry, I was confused since the https://fontawesome.com/icons/people-arrows?style=solid seem to indicate that the solid is free.

**Comment by mitchelloharawild** [comment]
My mistake, I'll look into it more.

**Comment by mitchelloharawild** [comment]
Seems to work for me, do you have the latest version of `fontawesome` downloaded?
You can update it with `download_fontawesome()`.

**Comment by ocelhay** [comment]
I downloaded the icon package today.
`
> library(icon)
> download_fontawesome()
trying URL 'https://github.com/FortAwesome/Font-Awesome/archive/master.zip'
downloaded 12.9 MB

✓ fontawesome updated to version 5.13.0
`

**Comment by mitchelloharawild** [comment]
Managed to reproduce it, thanks for the bug report!

**Comment by mitchelloharawild** [comment]
Hopefully it works better now. Fixed some bad practice for expression building in `icon_find()`.
