### ISSUE TITLE
Add hyperlink to icons

### ISSUE THREAD

**Issue by camilogarciabotero** [mitchelloharawild/icon#22]
Hi all,

Thanks for `icons` package, was wondering if one can add an hyperlink to the icons? If yes, can you please provide an example?

Thanks in advance,
Camilo.

**Comment by mitchelloharawild** [comment]
As far as I know, using icons wherever you would use text should work. For markdown:
```r
Icon with link: [`r icon::fontawesome("rocket", style = "solid")`](https://pkg.mitchelloharawild.com/icon/)
```

**Comment by camilogarciabotero** [comment]
Thanks Mitch!
