### ISSUE TITLE
Adding icon in cv using vitae package with awesome templet 

### ISSUE THREAD

**Issue by DanyangDai** [mitchelloharawild/icon#23]
using code  `r icon::fontawesome("rocket", style = "solid")` in the vitae package with awesome templet does not show in an ideal way. 
<img width="709" alt="Screenshot 2020-07-15 at 10 08 41 pm" src="https://user-images.githubusercontent.com/43340871/87543251-c00c5480-c6e7-11ea-9584-c9c1cef8a82e.png">
Need to resize icon and make it align with text.

**Comment by mitchelloharawild** [comment]
MRE

````
---
name: Marie
surname: Curie
position: "Professor"
address: "School of Physics & Chemistry, École Normale Supérieure"
phone: +1 22 3333 4444
www: mariecurie.com
email: "Marie.Curie@ens.fr"
twitter: mariecurie
github: mariecurie
linkedin: mariecurie
date: "`r format(Sys.time(), '%B %Y')`"
output: vitae::awesomecv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```

# Some stuff about me

`r icon::fontawesome("rocket", style = "solid")`
````

**Comment by mitchelloharawild** [comment]
Fixed in 7debd0c3635ee63d95c56bbabcceb85193442d1d, note that icons will not work in titles due to an issue with how titles are handled specifically in the awesomecv library. I believe this needs fixing in https://github.com/posquit0/Awesome-CV and cannot be fixed by this package.

**Comment by mitchelloharawild** [comment]
The issue with icons in titles is due to how the Awesome-CV template colours the first three letters of the title.

You can include icons in titles if you remove this feature by adding:

```latex
\renewcommand*{\sectionstyle}[1]{{\fontsize{16pt}{1em}\bodyfont\bfseries\color{text}#1}}
```

to the body of your document.

**Comment by mitchelloharawild** [comment]
````
---
name: Marie
surname: Curie
position: "Professor"
address: "School of Physics & Chemistry, École Normale Supérieure"
phone: +1 22 3333 4444
www: mariecurie.com
email: "Marie.Curie@ens.fr"
twitter: mariecurie
github: mariecurie
linkedin: mariecurie
date: "`r format(Sys.time(), '%B %Y')`"
output: vitae::awesomecv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```

\renewcommand*{\sectionstyle}[1]{{\fontsize{16pt}{1em}\bodyfont\bfseries\color{text}#1}}

# `r icon::fontawesome$solid$rocket` rocket in title

`r icon::fontawesome$solid$rocket` rocket in body
````

![image](https://user-images.githubusercontent.com/16127127/87643316-0f0cc500-c78e-11ea-9512-6287a0cfe5da.png)
