### ISSUE TITLE
Impossible to download Google Materials Icons

### ISSUE THREAD

**Issue by rgouveiamendes** [mitchelloharawild/icon#62]
I get this message:

Error in download.file(url, dl_file) : 
  download from 'https://github.com/google/material-design-icons/archive/master.zip' failed
In addition: Warning message:
In download.file(url, dl_file) :
  URL 'https://codeload.github.com/google/material-design-icons/zip/master': Timeout of 60 seconds was reached

**Comment by mitchelloharawild** [comment]
The Google Material Design icons are hosted within a very large repository (~500MB) which may take some time to download. In your case, it seems to take longer than the default download timeout option of 60 seconds. Try bumping this value up with `options(timeout = 300)` for a timeout of 300 seconds (5 minutes).
