### ISSUE TITLE
Signal to user to run `download_fontawesome(version = "dev")`

### ISSUE THREAD

**Issue by ddsjoberg** [mitchelloharawild/icon#67]
Hello! Thank you for making these cute icons easily available to us!

I recently got a new computer, and was running some old scripts that use the icons pkg. I kept seeing an error from `icons::fontawesome("twitter")` that there was a subscript out of bounds. The solution was to first run `download_fontawesome(version = "dev")`, but I was pretty confused for quite a while before remembering about this step.

I think it would be helpful if there was some error messaging reminding users this may be the solution. Perhaps something like this?

```r
icons::fontawesome("twitter")
#> Error: Subscript out of bounds
#> Have you run `download_fontawesome(version = "dev")` already?
```

Thanks again!

PS I am on Windows 10 if that matters

**Comment by ddsjoberg** [comment]
Awesome, thank you!

**Comment by mitchelloharawild** [comment]
Thanks for your suggestion! Definitely a more helpful error (and better code practices) was needed here :rocket:
