### ISSUE TITLE
provide a function to see all icons in a set

### ISSUE THREAD

**Issue by DataStrategist** [mitchelloharawild/icon#68]
Hi, I like the functionality of `icons::icon_find('home')`, but considering that there are small differences between this package and, for example, fontawesome, I think it would be cool to have a function that you can use to see all the icons that can be used for each family.

**Comment by mitchelloharawild** [comment]
Thanks for your suggestion.

This is related to #65, but to make this work better I'd like to finish #32 first.

I'm closing this since it is very similar to #65.
