### ISSUE TITLE
cannot open the connection download_fontawesome()

### ISSUE THREAD

**Issue by giabaio** [mitchelloharawild/icon#72]
Hi,
I am able to use `download_academicons()` but when I try the other possible set of icons, one way or another, things fail...
In particular, for fontawesome, I get
```
library(icons)
> download_fontawesome()
Error in open.connection(con, "rb") : 
  cannot open the connection to 'https://api.github.com/repos/FortAwesome/Font-Awesome/releases/latest'
In addition: Warning message:
In open.connection(con, "rb") :
  cannot open URL 'https://api.github.com/repos/FortAwesome/Font-Awesome/releases/latest': HTTP status was '403 Forbidden'
```

Am I missing something obvious? 
Thanks

**Comment by mitchelloharawild** [comment]
Strange, looks like you've been refused access to the GitHub API.
What happens when you try to access the API directly from the web browser (i.e. open https://api.github.com/repos/FortAwesome/Font-Awesome/releases/latest)?

**Comment by giabaio** [comment]
Not sure, really --- it's worked just​ now!
Nevermind!

---

Gianluca Baio
Professor of Statistics and Health Economics | Head of Department


Department of Statistical Science | University College London
1-19 Torrington Place, London, WC1E 6BT, UK
Twitter: @stats_ucl<https://twitter.com/stats_UCL> | Instagram: @stats_UCL<https://instagram.com/ucl.stats/>


Telephone: +44(0)20 7679 1248 (internal: 41248)
Website: http://www.homepages.ucl.ac.uk/~ucakgba
Blog: https://gianluca.statistica.it/blog/
Book a meeting with me: https://book.morgen.so/gianlucabaio/book-me


***@***.***>   [https://www.svgrepo.com/show/157815/twitter.svg] <https://twitter.com/gianlubaio>    [https://www.svgrepo.com/show/138936/linkedin.svg] <https://www.linkedin.com/in/gianluca-baio-b893879/>    [https://www.svgrepo.com/show/341847/github.svg] <https://github.com/giabaio>    [https://www.geol.umd.edu/styles/academicons-192/svg/arxiv.svg] <https://arxiv.org/a/baio_g_1.html>    [https://www.geol.umd.edu/styles/academicons-192/svg/orcid.svg] <https://orcid.org/0000-0003-4314-2570>    [https://www.svgrepo.com/show/40973/soundcloud.svg] <https://soundcloud.com/uclsound/sets/sample-space>

_____________________________________________

For Head of Department correspondence, please use ***@***.******@***.***>

[https://s1g.s3.amazonaws.com/3f32ef1962be41fb8943ee58d28cf3aa.png]

This email may reach you outside of your working hours. If that’s the case, please do not feel pressure to reply immediately.
________________________________

**Comment by mitchelloharawild** [comment]
Strange, glad it's working for you now.

**Comment by stanstrup** [comment]
This happens when the github API rate limit is exceeded. But it seems the GITHUB_PAT that remotes::install_* is using is not used by icons::download_*.
I don't know another way to get around this apart from waiting...
