### ISSUE TITLE
add support for Health Icons

### ISSUE THREAD

**Issue by tomjemmett** [mitchelloharawild/icon#73]
[https://healthicons.org](Health Icons) are CC0 licensed icons intended for use in health care related projects. It would be helpful to add support to this package for these icons.

I would be happy to look at implementing this if you feel like this would be a suitable addition to the package.

**Comment by mitchelloharawild** [comment]
This would be a welcome addition to the package if you would like to submit
a pull request. Thanks for suggesting this library of icons!
